" [[ Plug-in ]]
call plug#begin()

" [ File Management ]
Plug 'preservim/nerdtree', { 'on':  'NERDTreeToggle' }

" [ View ]
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" [ Code ]
Plug 'fatih/vim-go', { 'for': 'go', 'do': ':GoUpdateBinaries' }
Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }

" [ Productivity & Automation ]
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
"
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
"
Plug 'ycm-core/YouCompleteMe'

" [ Version Control ]
Plug 'tpope/vim-fugitive'

call plug#end()


" [[ settings ]]
" [ General ]
set number
syntax on
filetype on
filetype plugin on
filetype indent on
" Enable auto completion menu after pressing TAB.
set wildmenu
set wildmode=list:longest
" Make search case insensitive
set hlsearch
set incsearch
set ignorecase
set smartcase
" Real programmers don't use TABs but spaces
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab


" [ Plug-in setting ]
" airline
let g:airline_theme='fruit_punch'
" vim-go

" [ Plug-in map ]
" Nerdtree
nnoremap <C-n> :NERDTree<CR>
" Fzf
nnoremap <C-c> :Files<CR>
nnoremap <C-l> :Lines<CR>
