" [[ Plug-in ]]
call plug#begin()

" [ File Management ]
Plug 'preservim/nerdtree', { 'on':  'NERDTreeToggle' }

" [ View ]
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" [ Code ]
Plug 'fatih/vim-go'
Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }

" [ Productivity & Automation ]
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
"
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
"
Plug 'ycm-core/YouCompleteMe'

" [ Version Control ]
Plug 'tpope/vim-fugitive'

call plug#end()


" [[ settings ]]
" [ General ]
set encoding=utf-8
set number
syntax on
filetype on
filetype plugin on
filetype indent on
" Enable auto completion menu after pressing TAB.
set wildmenu
set wildmode=list:longest
" Make search case insensitive
set hlsearch
set incsearch
set ignorecase
set smartcase
" Real programmers don't use TABs but spaces
set tabstop=4
set softtabstop=4
set shiftwidth=4            " Number of spaces to use for each step of (auto)indent.
set shiftround
set expandtab

" [ built-in ]

" [ Plug-in setting ]
" airline
let g:airline_theme='fruit_punch'

" Nerdtree
nnoremap <C-n> :NERDTree<CR>

" Fzf
nnoremap <C-c> :Files<CR>
nnoremap <C-x> :Rg<CR>
"nnoremap <C-l> :Lines<CR>

" ultisnips
"   Trigger configuration. You need to change this to something other than <tab> if you use one of the following:
"   - https://github.com/Valloric/YouCompleteMe
"   - https://github.com/nvim-lua/completion-nvim
let g:UltiSnipsExpandTrigger="<c-o>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
"   If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

" YCM
let g:ycm_autoclose_preview_window_after_completion = 1   " close preview windown

" vim-go
let g:go_doc_balloon = 1
let g:go_doc_popup_window = 1

" [[ Extra setting based on platform ]]
" - linux
"colorscheme torte
